all :

clean:
 del prepro.exe prepro.obj math_functions.o string_functions.o

compile:
 cl prepro.c

mathtestfile:
 prepro -i math_functions.c -c
 
mathtestfile2:
 prepro -i math_functions.c
  
stringtestfile:
 prepro -i string_functions.c -c

stringtestfile2:
 prepro -i string_functions.c 
  
